version: "3.9"

services:
  app:
    build:
      context: .
      args: 
      - DEV=true
    ## reflect the changes made inside the container to the host
    volumes:
    - ./app:/app 
    ports:
    - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ## Match what we have as initial params into the db
    environment:
    - DB_HOST=db
    - DB_NAME=devdb
    - DB_USER=devuser
    - DB_PASSWORD=devpassword
    depends_on:
      - db
  db:
    image: postgres:13-alpine
     
    ## Volume mapping
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=devdb
    - POSTGRES_USER=devuser
    - POSTGRES_PASSWORD=devpassword

volumes:
  dev-db-data: 